{"name": "test_successful_login_and_logout", "status": "failed", "statusDetails": {"message": "AssertionError: Не удалось выполнить выход из системы\nassert False", "trace": "self = <tests.test_auth.TestAuthentication object at 0x000002B3B62BD3D0>\npage = <Page url='https://liner.dstepanyuk.dev.smte.am/office/?&daterange=09.03.2025%20-%2009.03.2025&period=default&orders-direction=all&lead_type=all&lead_uniq=all&call-direction=all&predictive=all'>\nconfig = {'apiUrl': 'https://liner.dstepanyuk.dev.smte.am/api/', 'baseUrl': 'https://liner.dstepanyuk.dev.smte.am/auth/', 'brow...password': 'wrong_password'}, 'valid_user': {'email': 'dstepanyuk@southmedia.io', 'password': 'yND-jC2-rWz-qqJ'}}, ...}\n\n    @allure.story(\"Successful login and logout\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_successful_login_and_logout(self, page, config):\n        \"\"\"Проверка успешной авторизации и выхода из системы\"\"\"\n        login_page = LoginPage(page, config.get(\"baseUrl\"))\n    \n        with allure.step(\"Переход на страницу логина\"):\n            login_page.navigate()\n    \n        with allure.step(\"Ввод учетных данных и вход\"):\n            valid_credentials = config['credentials']['valid_user']\n            login_page.login(valid_credentials['email'], valid_credentials['password'])\n    \n        with allure.step(\"Проверка успешной авторизации\"):\n            expected_url = \"https://liner.dstepanyuk.dev.smte.am/office/\"\n            page.wait_for_url(f\"**{expected_url}*\", timeout=10000)\n            assert expected_url in page.url, f\"Ожидался URL с '/office/', но получен {page.url}\"\n    \n        with allure.step(\"Выполнение выхода из системы\"):\n            logout_success = login_page.logout()\n>           assert logout_success, \"Не удалось выполнить выход из системы\"\nE           AssertionError: Не удалось выполнить выход из системы\nE           assert False\n\ntests\\test_auth.py:28: AssertionError"}, "description": "Проверка успешной авторизации и выхода из системы", "steps": [{"name": "Переход на страницу логина", "status": "passed", "start": 1741525390988, "stop": 1741525392646}, {"name": "Ввод учетных данных и вход", "status": "passed", "start": 1741525392646, "stop": 1741525393620}, {"name": "Проверка успешной авторизации", "status": "passed", "start": 1741525393620, "stop": 1741525395591}, {"name": "Выполнение выхода из системы", "status": "failed", "statusDetails": {"message": "AssertionError: Не удалось выполнить выход из системы\nassert False\n", "trace": "  File \"E:\\automation\\tests\\test_auth.py\", line 28, in test_successful_login_and_logout\n    assert logout_success, \"Не удалось выполнить выход из системы\"\n"}, "start": 1741525395591, "stop": 1741525425682}], "attachments": [{"name": "stdout", "source": "a0d5ebc3-6bbe-4b0f-9527-105f0ed57255-attachment.txt", "type": "text/plain"}], "start": 1741525390988, "stop": 1741525425683, "uuid": "4b60e3a4-6b06-419d-8765-b48d4fbd627d", "historyId": "ae68f5a78a693dc1d0419302ec8d8402", "testCaseId": "ae68f5a78a693dc1d0419302ec8d8402", "fullName": "tests.test_auth.TestAuthentication#test_successful_login_and_logout", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Authentication"}, {"name": "story", "value": "Successful login and logout"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-US86AEC"}, {"name": "thread", "value": "5252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}