{"name": "test_invalid_login", "status": "passed", "description": "Проверка отказа в авторизации с неправильными учетными данными", "steps": [{"name": "Переход на страницу логина", "status": "passed", "start": 1741679338236, "stop": 1741679340153}, {"name": "Ввод неверных учетных данных", "status": "passed", "start": 1741679340153, "stop": 1741679341405}, {"name": "Проверка сообщения об ошибке", "status": "passed", "start": 1741679341405, "stop": 1741679341584}], "start": 1741679338236, "stop": 1741679341584, "uuid": "e20c8d33-219a-4c87-bc81-4f1a35429eb5", "historyId": "82a3aecb15cbccc5f57469d68a4a256a", "testCaseId": "82a3aecb15cbccc5f57469d68a4a256a", "fullName": "tests.test_auth.TestAuthentication#test_invalid_login", "labels": [{"name": "feature", "value": "Authentication"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Invalid login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-US86AEC"}, {"name": "thread", "value": "14460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}